# Generated by Django 4.1.5 on 2023-01-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroiMarvel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('img', models.ImageField(upload_to='imagem')),
            ],
        ),
        migrations.DeleteModel(
            name='Heroi',
        ),
    ]
